site_name: Diogo André Silvares Dias
site_author: das-dias
site_description: "A personal landing page built on top of MkDocs documentation framework."
site_url: https://das-dias.github.io/

validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn

nav:
  - Home: index.md
  - Miscellaneous: misc.md
  - Signal-Converters: signal_converters.md
  - Signoff Tools: signoff_tools.md
  #- Computational Electromagnetics: computational_electromagnetics.md

theme:
  name: slate
  locale: en
  highlightjs: true
  hljs_style: night-owl
  hljs_style_dark: github-dark
  #hljs_languages:
  #  - yaml
  #  - toml
  #  - c
  #  - python

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

plugins: 
  - search
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - mathjaxhelper.js