# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"
theme = "system"
# This page should be the root of your website. It's important.
page = "https://das-dias.notion.site/Diogo-Andr-83a5addb4ab74ac79953218b61deeaeb"

[site]
  [[site.meta]]
  name = "Diogo Andre's Web CV"
  description = "A personal web landing page to summarize my CV."
